version: '3'

services:
#  app:
#    image: nginx:stable-alpine
#    volumes:
#    - ./dist:/usr/share/nginx/html
#    - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#    - 80:80
#    restart: always

  node:
    build: ./docker
    volumes:
    - .:/code
    - '${HOME}/.cache/yarn:/usr/local/share/.cache/yarn/'
    working_dir: /code
    ports:
    - 8080:8080
    command: yarn serve
networks:
  default:
    external:
      name: gusgo-net

